name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: nightly
        profile: minimal

    - name: Install LLVM tools
      run: |
        sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        sudo ln -s /usr/bin/llvm-cov-13 /usr/bin/llvm-cov
        sudo ln -s /usr/bin/llvm-profdata-13 /usr/bin/llvm-profdata

    - name: Generate Coverage
      run: |
        sh cov.sh --json
        sh cov.sh --html

    - name: Move to Deploy Directory
      run: |
        mkdir out
        mv cov.json out/cov.json
        mv cov/rustc-semver/* out/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN  }}
        publish_dir: ./out
        user_name: "GHA CI"
        user_email: "gha@users.noreply.github.com"
        commit_message: "Automatic deploy of coverage report"
